apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: one-quant

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - pvc.yaml
  - deployment-api.yaml
  - deployment-runner.yaml
  - deployment-risk.yaml
  - deployment-collector.yaml
  - deployment-ai.yaml
  - service-api.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: one-quant
  app.kubernetes.io/version: "0.1.0"
